### PR TITLE
Fix url generation; Make tld() public

### PR DESCRIPTION
**Pull request by jasonmead**

### CODE REVIEW

**Comment by bpholt** [comment]
Since this is a bug fix, can you change the version in `version.sbt` to 

```scala
version in ThisBuild := "1.11.1-SNAPSHOT"
```

**Comment by therockstorm** [comment]
Updated @bpholt, we good?

**Comment by bpholt** [comment]
@therockstorm Why is it `1.12.1`? We haven't released a `1.12.0` for this project yet.

**Comment by therockstorm** [comment]
It was 1.12.0 and I got confused. Updated.

**Pull request merged**
